CI work - update

diff --git a/.ci/jenkins/build-test/Jenkinsfile b/.ci/jenkins/build-test/Jenkinsfile
--- a/.ci/jenkins/build-test/Jenkinsfile
+++ b/.ci/jenkins/build-test/Jenkinsfile
@@ -21,6 +21,65 @@ pipeline {
                      required: true)
     }
     stages {
+        stage('Scan for possible secrets'){
+            steps{
+                sh label: "Secrets scan",
+                   script: """
+                   #!/bin/bash
+
+                    if [ ! -f .secrets.baseline ] ;
+                    then
+                        # This generated baseline file will only be temporarily available on the GitHub side and will not appear in the user's local files.
+                        # Scanning an empty folder to generate an initial .secrets.baseline without secrets in the results.
+                        echo "⚠️ No existing .secrets.baseline file detected. Creating a new blank baseline file."
+                        mkdir empty-dir
+                        detect-secrets scan empty-dir > .secrets.baseline
+                        echo "✅ Blank .secrets.baseline file created successfully."
+                        rm -r empty-dir
+                    else
+                        echo "✅ Existing .secrets.baseline file detected. No new baseline file will be created."
+                    fi
+                    # scripts scan repository for new secrets
+                    # backup list of known secrets
+                    cp -pr .secrets.baseline .secrets.new
+                    # find secrets in the repository
+                    detect-secrets scan --disable-plugin AbsolutePathDetectorExperimental --all-files --baseline .secrets.new \
+                        --exclude-files '\\.secrets..*' \
+                        --exclude-files '\\.git.*' \
+                        --exclude-files 'test_results'
+                    # break build when new secrets discovered
+                    # function compares baseline/new secrets w/o listing results -- success(0) when new secret found
+                    """
+
+                archiveArtifacts artifacts: ".secrets.new", allowEmptyArchive: true, fingerprint: true
+
+                sh label: "Compare scan result to baseline",
+                   script: """
+                   #!/bin/bash
+
+                    source .ci/scripts/util/compare_secrets_baselines.sh
+                    # test baseline versus new secret files
+                    if compare_secrets .secrets.baseline .secrets.new;
+                    then
+                        echo "⚠️ Attention Required! ⚠️" >&2
+                        echo "New secrets have been detected in your recent commit. Due to security concerns, we cannot display detailed information here and we cannot proceed until this issue is resolved." >&2
+                        echo "" >&2
+                        echo "Please follow the steps below on your local machine to reveal and handle the secrets:" >&2
+                        echo "" >&2
+                        echo "1️⃣ Run the 'detect-secrets' tool on your local machine. This tool will identify and clean up the secrets. You can find detailed instructions at this link: https://nasa-ammos.github.io/slim/continuous-testing/starter-kits/#detect-secrets" >&2
+                        echo "" >&2
+                        echo "2️⃣ After cleaning up the secrets, commit your changes and re-push your update to the repository." >&2
+                        echo "" >&2
+                        echo "Your efforts to maintain the security of our codebase are greatly appreciated!" >&2
+                        exit 1
+                    else
+                        echo "🟢 Secrets tests PASSED! 🟢" >&1
+                        echo "No new secrets were detected in comparison to any baseline configurations."  >&1
+                        exit 0
+                    fi
+                   """
+            }
+        }
         stage('Build OPERA PGE Docker image(s)') {
             steps {
                 script {
@@ -77,64 +136,6 @@ pipeline {
 
                     archiveArtifacts artifacts: 'test_results/**/grype_vulnerabilities.html', fingerprint: true
                 }
-            }
-        }
-        stage('Scan for possible secrets'){
-            steps{
-                sh label: "Secrets scan",
-                   script: """
-                   #!/bin/bash
-
-                    if [ ! -f .secrets.baseline ] ;
-                    then
-                        # This generated baseline file will only be temporarily available on the GitHub side and will not appear in the user's local files.
-                        # Scanning an empty folder to generate an initial .secrets.baseline without secrets in the results.
-                        echo "⚠️ No existing .secrets.baseline file detected. Creating a new blank baseline file."
-                        mkdir empty-dir
-                        detect-secrets scan empty-dir > .secrets.baseline
-                        echo "✅ Blank .secrets.baseline file created successfully."
-                        rm -r empty-dir
-                    else
-                        echo "✅ Existing .secrets.baseline file detected. No new baseline file will be created."
-                    fi
-                    # scripts scan repository for new secrets
-                    # backup list of known secrets
-                    cp -pr .secrets.baseline .secrets.new
-                    # find secrets in the repository
-                    detect-secrets scan --disable-plugin AbsolutePathDetectorExperimental --all-files --baseline .secrets.new \
-                        --exclude-files '\\.secrets..*' \
-                        --exclude-files '\\.git.*' \
-                    # break build when new secrets discovered
-                    # function compares baseline/new secrets w/o listing results -- success(0) when new secret found
-                    """
-
-                archiveArtifacts artifacts: ".secrets.new", allowEmptyArchive: true, fingerprint: true
-
-                sh label: "Compare scan result to baseline",
-                   script: """
-                   #!/bin/bash
-
-                    source .ci/scripts/util/compare_secrets_baselines.sh
-                    # test baseline versus new secret files
-                    if compare_secrets .secrets.baseline .secrets.new;
-                    then
-                        echo "⚠️ Attention Required! ⚠️" >&2
-                        echo "New secrets have been detected in your recent commit. Due to security concerns, we cannot display detailed information here and we cannot proceed until this issue is resolved." >&2
-                        echo "" >&2
-                        echo "Please follow the steps below on your local machine to reveal and handle the secrets:" >&2
-                        echo "" >&2
-                        echo "1️⃣ Run the 'detect-secrets' tool on your local machine. This tool will identify and clean up the secrets. You can find detailed instructions at this link: https://nasa-ammos.github.io/slim/continuous-testing/starter-kits/#detect-secrets" >&2
-                        echo "" >&2
-                        echo "2️⃣ After cleaning up the secrets, commit your changes and re-push your update to the repository." >&2
-                        echo "" >&2
-                        echo "Your efforts to maintain the security of our codebase are greatly appreciated!" >&2
-                        exit 1
-                    else
-                        echo "🟢 Secrets tests PASSED! 🟢" >&1
-                        echo "No new secrets were detected in comparison to any baseline configurations."  >&1
-                        exit 0
-                    fi
-                   """
             }
         }
     }
